spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.130:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n/login
# 禁用缓存
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

